### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Te-k** [botherder/snoopdigg#2] opened 2019-11-21 19:04 UTC
I encountered a bug while using Snoopdigg, I think it was due to a very weird startup entry and I don't have access to the computer anymore, so it may be hard to debug, but here it is :

```
                                | (_)
 ___ _ __   ___   ___  _ __   __| |_  __ _  __ _
/ __| '_ \ / _ \ / _ \| '_ \ / _` | |/ _` |/ _` |
\__ \ | | | (_) | (_) | |_) | (_| | | (_| | (_| |
|___/_| |_|\___/ \___/| .__/ \__,_|_|\__, |\__, |
                      | |             __/ | __/ |
                      |_|            |___/ |___/
    (c) 2017-2018 Claudio Guarnieri (nex@nex.sx)

panic: exit status -1073740791

goroutine 1 [running]:
github.com/matishsiao/goInfo.GetInfo(0x40df8c)
        /home/user/.gvm/pkgsets/go1.9.2/global/src/github.com/matishsiao/goInfo/goInfo_windows.go:20 +0x4e0
main.getOperatingSystem(0x10f8fbe0, 0xc)
        /home/user/src/snoopdigg/utils.go:39 +0x1e
main.(*Acquisition).Initialize(0x7d5fe0)
        /home/user/src/snoopdigg/acquisition.go:40 +0x228
main.main()
        /home/user/src/snoopdigg/main.go:31 +0x31
```

**Comment by botherder** [comment] 2020-08-05 18:39
I suspect this was an issue with goInfo, and I can't reproduce this. Closing for now.

**Closed as completed by botherder** 2020-08-05 18:39 UTC
